const changeBackgroundImage = () => {
    // document.body.style.backgroundImage = "url('background-corgi-sleep.jpg')"
    // document.body.appendChild = "<h1>Hello</h1>"
}

document.addEventListener('DOMContentLoaded', () => {   
    changeBackgroundImage()
    document.addEventListener('mousemove', (e)=>console.log(e.x, e.y))
})

//when 1189x741
// x1, y1 478, 139 clamp // 40%, 19%
// x1, y1 533, 150 cover // 45%, 20%

// x2, y2 573, 221 clamp // 48%, 30%
// x2 y2 629, 245 cover // 53%, 33%
{/* <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 1080">
  <image width="1920" height="1080" xlink:href="background-corgi-sleep.jpg"></image> <a xlink:href="#">
    <rect x="773" y="207" fill="#fff" opacity="0" width="164" height="151"></rect>
  </a><a xlink:href="#">
    <rect x="139" y="709" fill="#fff" opacity="0" width="142" height="144"></rect>
  </a><a xlink:href="#">
    <rect x="289" y="608" fill="#fff" opacity="0" width="151" height="145"></rect>
  </a><a xlink:href="#">
    <rect x="757" y="642" fill="#fff" opacity="0" width="166" height="167"></rect>
  </a><a xlink:href="#">
    <rect x="1222" y="449" fill="#fff" opacity="0" width="196" height="207"></rect>
  </a>
</svg>  */}

// <!-- Image Map Generated by http://www.image-map.net/ -->
// <img src="background-corgi-sleep.jpg" usemap="#image-map">

// <map name="image-map">
//     <area target="" alt="" title="" href="" coords="771,285,840,216,983,182,1054,260,1020,348,845,356" shape="poly">
//     <area target="" alt="" title="" href="" coords="762,782,764,704,895,600,1007,570,1103,643,1041,766,846,817" shape="poly">
//     <area target="" alt="" title="" href="" coords="274,666,254,604,306,576,377,593,416,722,355,754" shape="poly">
//     <area target="" alt="" title="" href="" coords="157,722,228,712,276,754,271,843,230,858,172,812,153,771" shape="poly">
//     <area target="" alt="" title="" href="" coords="1317,402,1473,339,1649,417,1722,614,1656,763,1580,792,1524,763,1397,797,1205,743,1215,527" shape="poly">
// </map>